version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
  build:
    commands:
      - echo Build started on `date`
      
      
      - dotnet restore back/ResourcesLambda/Monitor.Core/Monitor.Core.csproj
      - dotnet restore back/ResourcesLambda/Monitor.Infra/Monitor.Infra.csproj
      - dotnet restore back/ResourcesLambda/Monitor.Service/Monitor.Service.csproj

      - dotnet build back/ResourcesLambda/Monitor.Core/Monitor.Core.csproj
      - dotnet build back/ResourcesLambda/Monitor.Infra/Monitor.Infra.csproj
      - dotnet build back/ResourcesLambda/Monitor.Service/Monitor.Service.csproj
      
      - dotnet publish Monitor.Service.csproj -o bin/Release/netcoreapp3.1
      - aws s3 sync bin/Release/netcoreapp3.1/publish "s3://resource-management-staging/MonitorServices"
artifacts:
  files:
    - .\bin\Release\netcoreapp3.1\*      

