version: 0.2
env:
  variables:
    S3_BUCKET: "monitor-prod"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd front
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
      - npm install -g @aws-amplify/cli
      - amplify init
      - amplify configure
      - amplify env pull
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=staging --aot
  post_build:
     commands:
      - aws s3 cp dist/front s3://monitor-prod --recursive
      - echo Build completed on `date`
