version: 0.2
env:
  variables:
    S3_BUCKET: "monitor-prod"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd front
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - aws s3 cp dist/front s3://monitor-prod --recursive
      - aws cloudfront create-invalidation --distribution-id E13GE1GMAJKUBE \ --paths /index.html /error.html
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
