version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
  build:
    commands:
      - echo Build started on `date`
      
      
      - dotnet restore back/ResourcesLambda/Monitor.Core/Monitor.Core.csproj
      - dotnet restore back/ResourcesLambda/Monitor.Infra/Monitor.Infra.csproj
      - dotnet restore back/ResourcesLambda/Monitor.Service/Monitor.Service.csproj

      - dotnet build back/ResourcesLambda/Monitor.Core/Monitor.Core.csproj
      - dotnet build back/ResourcesLambda/Monitor.Infra/Monitor.Infra.csproj
      - dotnet build back/ResourcesLambda/Monitor.Service/Monitor.Service.csproj
      
      - dotnet publish back/ResourcesLambda/Monitor.Service/Monitor.Service.csproj -o back/ResourcesLambda/Monitor.Service/bin/Debug/netcoreapp3.1
artifacts:
  files:
    - back\ResourcesLambda\Monitor.Service\bin\Debug\netcoreapp3.1\*      

