version: 0.2
env:
  variables:
    S3_BUCKET: "monitor-stage"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd front
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
      - amplify update project
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=staging --aot
  post_build:
     commands:
      - aws s3 cp dist/front s3://monitor-stage --recursive
      - echo aws cloudfront create-invalidation --distribution-id E13GE1GMAJKUBE \ --paths /index.html /error.html
      - echo Build completed on `date`

