version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd back
      - dotnet build
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish Api/Api.csproj -o bin/Release/netcoreapp2.1/publish
      - ls
      - cd Api

artifacts:
  files:
    - outputSamTemplate.yml
  discard-paths: yes
  base-directory: Api
