version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - cd back/ResourcesLambda/ResourcesLambda
      - dotnet build
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish ResourcesLambda.csproj -o bin/Release/netcoreapp2.1/publish

