version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: latest
  build:
    commands:
      - echo Build started on `date`
      
      - dotnet restore back/monitor-back/monitor-core/monitor-core.csproj
      - dotnet restore back/monitor-back/monitor-infra/monitor-infra.csproj
      - dotnet restore back/monitor-back/monitor-back/monitor-back.csproj

      - dotnet build back/monitor-back/monitor-core/monitor-core.csproj
      - dotnet build back/monitor-back/monitor-infra/monitor-infra.csproj
      - dotnet build back/monitor-back/monitor-back/monitor-back.csproj
      
      - dotnet publish back/monitor-back/monitor-back.csproj -o back/monitor-back/bin/Release/netcoreapp3.1
artifacts:
  files:
   - '**/*' 
  base-directory: back\monitor-back\bin\Release\netcoreapp3.1      

