// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:86c0ec5d-a7d0-4a0e-8c92-307863f4b280",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NwDySt6wd",
    "aws_user_pools_web_client_id": "1uq198peafb90bg68iqfdcp7lg",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
