// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0976865c-00f9-4218-aeea-2a80ec6a93a0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OoOivDwjA",
    "aws_user_pools_web_client_id": "17ll1achpiig7nmtbl7s94tem9",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "resources-staging",
            "region": "us-east-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "resources",
            "endpoint": "https://bxzqq9jo95.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
